app = "yu-goatcounter"
primary_region = "hkg"

[build]

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = false
auto_start_machines = true
min_machines_running = 1
processes = ["app"]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 256

[env]
PORT = "8080"
GOATCOUNTER_DB = "sqlite3://data/goatcounter.sqlite3"

[mounts]
source = "goatcounter_data"
destination = "/data"
